spring.application.name=admin-service
server.port=${ADMIN_SERVICE_PORT:8090}

spring.security.oauth2.resourceserver.jwt.secret-key=${JWT_SECRET:0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef}

admin.catalog.base-url=${CATALOG_SERVICE_URL:http://localhost:8083}

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
